const chartPalette = ["#004b8d", "#1f7f9b", "#69a8cf", "#63758c", "#356f92", "#9aaec2"];
const newMemberColor = "#69a8cf";
const renewalColor = "#004b8d";
const analysisCopy = {
  growth: {
    title: "Member acquisition by category",
    description: "See which qualified membership categories are contributing the most new members.",
  },
  retention: {
    title: "Monthly renewal retention percentage",
    description: "Track renewal rate movement across the months that have reported activity.",
  },
  revenue: {
    title: "Membership revenue by month",
    description: "Compare month-by-month revenue generated by annual and lifetime membership activity.",
  },
  regions: {
    title: "Regions leading in member acquisition",
    description: "Identify the regions driving the highest combined new-member and renewal activity.",
  },
  composition: {
    title: "Acquisition and renewal mix",
    description: "Understand how new members and renewals contribute to each monthâ€™s total activity.",
  },
};
const tableCopy = {
  months: {
    title: "Strongest months by total activity",
    description: "Ranked months with new members, renewals, total activity, revenue, and relative activity level.",
  },
  expirations: {
    title: "Expiration pipeline by region",
    description: "Regional expiration volume with the earliest and latest dates represented in the current pipeline.",
  },
  active: {
    title: "Active members by type",
    description: "Active member volume by qualified membership type, with relative share shown for quick comparison.",
  },
};

document.addEventListener("DOMContentLoaded", () => {
  renderDashboard(window.dashboardData);
  setupInteractions();
});

function renderDashboard(data) {
  document.getElementById("report-title").textContent = data.title;
  document.getElementById("report-summary").textContent = data.summary;
  document.getElementById("report-period").textContent = data.currentPeriod;

  setKpi("kpi-new-members", data.kpis.newMembers, formatInteger);
  setKpi("kpi-renewals", data.kpis.renewals, formatInteger);
  setKpi("kpi-revenue", data.kpis.revenue, formatCurrency);
  setKpi("kpi-active-members", data.kpis.activeMembers, formatInteger);
  setKpi("kpi-expiring", data.kpis.expiring, formatInteger);

  renderBriefing(data);
  renderSignals(data);
  renderAcquisitionByCategory(data.newMembersSeries);
  renderRenewalRateChart(data.renewalRateSeries);
  renderRevenueChart(data.visibleMonths, data.revenueSeries);
  renderRegionsChart(data.topRegions);
  renderMemberMixChart(data.memberMix);

  renderTopMonthsTable(data.topMonths);
  renderExpirationTable(data.expirationPipeline);
  renderActiveMembersTable(data.activeMembers);
}

function renderBriefing(data) {
  const topMonth = data.topMonths[0];
  const topRegion = data.topRegions[0];
  const strongestCategory = [...data.newMembersSeries].sort((a, b) => b.total - a.total)[0];
  const latestRetention = data.renewalRateSeries[data.renewalRateSeries.length - 1];
  const activeLeader = data.activeMembers[0];

  document.getElementById("briefing-copy").innerHTML = `
    <section class="briefing-block">
      <h3>Portfolio snapshot</h3>
      <ul>
        <li>${data.period} currently shows ${formatInteger(data.kpis.newMembers)} new members and ${formatInteger(data.kpis.renewals)} renewals.</li>
        <li>Membership revenue stands at ${formatCurrency(data.kpis.revenue)} through ${data.currentThrough.replace("Current through ", "")}.</li>
        <li>${formatInteger(data.kpis.expiring)} members are represented in the current expiration pipeline.</li>
      </ul>
    </section>
    <section class="briefing-block">
      <h3>Momentum</h3>
      <ul>
        <li>${topMonth.month} is the strongest month so far with ${formatInteger(topMonth.totalMembers)} total member actions.</li>
        <li>${strongestCategory.membership} leads category acquisition with ${formatInteger(strongestCategory.total)} new members.</li>
        <li>${topRegion.region} leads regional activity with ${formatInteger(topRegion.totalMembers)} total member actions.</li>
      </ul>
    </section>
    <section class="briefing-block">
      <h3>Retention and base</h3>
      <ul>
        <li>The latest reported renewal retention rate is ${formatPercent(latestRetention.rate)} for ${latestRetention.month}.</li>
        <li>${activeLeader.membershipType} is the largest active member type with ${formatInteger(activeLeader.totalMembers)} members.</li>
      </ul>
    </section>
  `;
}

function renderSignals(data) {
  const topMonth = data.topMonths[0];
  const topRegion = data.topRegions[0];
  const activeLeader = data.activeMembers[0];
  const latestRetention = data.renewalRateSeries[data.renewalRateSeries.length - 1];
  const firstExpiration = data.expirationPipeline[0];

  const signals = [
    {
      title: "Top month",
      subtitle: `${topMonth.month} leads total activity`,
      value: formatInteger(topMonth.totalMembers),
    },
    {
      title: "Top region",
      subtitle: `${topRegion.region} leads acquisition activity`,
      value: formatInteger(topRegion.totalMembers),
    },
    {
      title: "Latest retention",
      subtitle: `${latestRetention.month} renewal retention percentage`,
      value: formatPercent(latestRetention.rate),
    },
    {
      title: "Largest active type",
      subtitle: activeLeader.membershipType,
      value: formatInteger(activeLeader.totalMembers),
    },
    {
      title: "Expiration concentration",
      subtitle: firstExpiration.region,
      value: formatInteger(firstExpiration.members),
    },
  ];

  document.getElementById("signal-list").innerHTML = signals.map((signal, index) => `
    <div class="signal-row">
      <span class="signal-rank">${index + 1}</span>
      <span>
        <span class="signal-title">${escapeHtml(signal.title)}</span>
        <span class="signal-subtitle">${escapeHtml(signal.subtitle)}</span>
      </span>
      <span class="signal-value">${escapeHtml(signal.value)}</span>
    </div>
  `).join("");
}

function setupInteractions() {
  document.querySelectorAll(".view-tab").forEach((button) => {
    button.addEventListener("click", () => {
      const view = button.dataset.view;
      document.querySelectorAll(".view-tab").forEach((tab) => tab.classList.toggle("is-active", tab === button));
      document.querySelectorAll(".analysis-panel").forEach((panel) => {
        panel.classList.toggle("is-active", panel.dataset.panel === view);
      });
      document.getElementById("analysis-title").textContent = analysisCopy[view].title;
      document.getElementById("analysis-description").textContent = analysisCopy[view].description;
    });
  });

  document.querySelectorAll(".table-tab").forEach((button) => {
    button.addEventListener("click", () => {
      const table = button.dataset.table;
      document.querySelectorAll(".table-tab").forEach((tab) => tab.classList.toggle("is-active", tab === button));
      document.querySelectorAll(".table-panel").forEach((panel) => {
        panel.classList.toggle("is-active", panel.dataset.tablePanel === table);
      });
      document.getElementById("table-title").textContent = tableCopy[table].title;
      document.getElementById("table-description").textContent = tableCopy[table].description;
    });
  });
}

function renderAcquisitionByCategory(series) {
  renderHorizontalBars("new-members-chart", series.map((item, index) => ({
    label: item.membership,
    value: item.total,
    color: chartPalette[index % chartPalette.length],
  })), { valueFormatter: formatInteger });
}

function renderRenewalRateChart(series) {
  renderLineChart("renewal-rate-chart", series.map((item) => ({
    label: item.month,
    value: item.rate,
  })), {
    color: "#004b8d",
    valueFormatter: formatPercent,
    maxValue: 100,
  });
}

function renderRevenueChart(months, series) {
  const totals = months.map((month, index) => ({
    label: month,
    value: series.reduce((total, item) => total + item.monthly[index], 0),
  }));
  renderVerticalBars("revenue-chart", totals, {
    color: "#1f7f9b",
    valueFormatter: formatCompactCurrency,
  });
}

function renderRegionsChart(regions) {
  renderHorizontalBars("regions-chart", regions.map((item) => ({
    label: item.region,
    value: item.totalMembers,
    color: "#007d8c",
  })), { valueFormatter: formatInteger });
}

function renderMemberMixChart(series) {
  renderStackedBars("member-mix-chart", series.map((item) => ({
    label: item.month,
    segments: [
      { label: "New members", value: item.New, color: newMemberColor },
      { label: "Renewals", value: item.Renewal, color: renewalColor },
    ],
  })));
}

function renderHorizontalBars(id, rows, { valueFormatter }) {
  const target = document.getElementById(id);
  if (!rows.length) {
    target.innerHTML = "<div class=\"chart-empty\">No data available</div>";
    return;
  }

  const max = Math.max(...rows.map((row) => row.value), 1);

  target.innerHTML = `
    <div class="hbar-chart" role="img" aria-label="Horizontal bar chart">
      ${rows.map((row, index) => {
        const width = Math.max((row.value / max) * 100, 1);
        return `
          <div class="hbar-row">
            <div class="hbar-label">${escapeHtml(row.label)}</div>
            <div class="hbar-track">
              <div class="hbar-fill" style="width: ${width}%; background: ${row.color};"></div>
            </div>
            <div class="hbar-value">${valueFormatter(row.value)}</div>
          </div>
        `;
      }).join("")}
    </div>
  `;
}

function renderVerticalBars(id, rows, { color, valueFormatter }) {
  const target = document.getElementById(id);
  const width = 620;
  const height = 320;
  const pad = { top: 24, right: 24, bottom: 46, left: 58 };
  const max = Math.max(...rows.map((row) => row.value), 1);
  const chartHeight = height - pad.top - pad.bottom;
  const slot = (width - pad.left - pad.right) / rows.length;
  const barWidth = Math.min(56, slot * 0.58);

  target.innerHTML = `
    <svg class="svg-chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="Vertical bar chart">
      <line class="chart-axis" x1="${pad.left}" y1="${height - pad.bottom}" x2="${width - pad.right}" y2="${height - pad.bottom}"></line>
      ${rows.map((row, index) => {
        const h = (row.value / max) * chartHeight;
        const x = pad.left + slot * index + (slot - barWidth) / 2;
        const y = height - pad.bottom - h;
        return `
          <rect x="${x}" y="${y}" width="${barWidth}" height="${h}" rx="4" fill="${color}"></rect>
          <text class="chart-subtle" x="${x + barWidth / 2}" y="${y - 8}" text-anchor="middle">${valueFormatter(row.value)}</text>
          <text class="chart-label" x="${x + barWidth / 2}" y="${height - 18}" text-anchor="middle">${escapeHtml(row.label)}</text>
        `;
      }).join("")}
    </svg>
  `;
}

function renderLineChart(id, rows, { color, valueFormatter, maxValue }) {
  const target = document.getElementById(id);
  const width = 620;
  const height = 320;
  const pad = { top: 28, right: 28, bottom: 46, left: 48 };
  const max = maxValue || Math.max(...rows.map((row) => row.value), 1);
  const chartWidth = width - pad.left - pad.right;
  const chartHeight = height - pad.top - pad.bottom;
  const points = rows.map((row, index) => {
    const x = pad.left + (chartWidth / Math.max(rows.length - 1, 1)) * index;
    const y = pad.top + chartHeight - (row.value / max) * chartHeight;
    return { ...row, x, y };
  });
  const path = points.map((point, index) => `${index === 0 ? "M" : "L"} ${point.x} ${point.y}`).join(" ");

  target.innerHTML = `
    <svg class="svg-chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="Line chart">
      <line class="chart-axis" x1="${pad.left}" y1="${height - pad.bottom}" x2="${width - pad.right}" y2="${height - pad.bottom}"></line>
      <path d="${path}" fill="none" stroke="${color}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"></path>
      ${points.map((point) => `
        <circle cx="${point.x}" cy="${point.y}" r="5" fill="${color}"></circle>
        <text class="chart-subtle" x="${point.x}" y="${point.y - 12}" text-anchor="middle">${valueFormatter(point.value)}</text>
        <text class="chart-label" x="${point.x}" y="${height - 18}" text-anchor="middle">${escapeHtml(point.label)}</text>
      `).join("")}
    </svg>
  `;
}

function renderStackedBars(id, rows) {
  const target = document.getElementById(id);
  const width = 620;
  const height = 320;
  const pad = { top: 24, right: 24, bottom: 46, left: 42 };
  const max = Math.max(...rows.map((row) => row.segments.reduce((total, segment) => total + segment.value, 0)), 1);
  const chartHeight = height - pad.top - pad.bottom;
  const slot = (width - pad.left - pad.right) / rows.length;
  const barWidth = Math.min(60, slot * 0.6);

  target.innerHTML = `
    <div class="chart-legend">
      <span class="legend-item"><span class="legend-swatch" style="background: ${newMemberColor};"></span>New members</span>
      <span class="legend-item"><span class="legend-swatch" style="background: ${renewalColor};"></span>Renewals</span>
    </div>
    <svg class="svg-chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="Stacked bar chart">
      <line class="chart-axis" x1="${pad.left}" y1="${height - pad.bottom}" x2="${width - pad.right}" y2="${height - pad.bottom}"></line>
      ${rows.map((row, index) => {
        const x = pad.left + slot * index + (slot - barWidth) / 2;
        let y = height - pad.bottom;
        const bars = row.segments.map((segment) => {
          const h = (segment.value / max) * chartHeight;
          y -= h;
          return `<rect x="${x}" y="${y}" width="${barWidth}" height="${h}" rx="3" fill="${segment.color}"></rect>`;
        }).join("");
        const total = row.segments.reduce((sum, segment) => sum + segment.value, 0);
        return `
          ${bars}
          <text class="chart-subtle" x="${x + barWidth / 2}" y="${y - 8}" text-anchor="middle">${formatInteger(total)}</text>
          <text class="chart-label" x="${x + barWidth / 2}" y="${height - 18}" text-anchor="middle">${escapeHtml(row.label)}</text>
        `;
      }).join("")}
    </svg>
  `;
}

function renderTopMonthsTable(rows) {
  const max = Math.max(...rows.map((row) => row.totalMembers), 1);
  renderTable("top-months-table", [
    { label: "Rank", render: (row) => `<span class="pill">#${row.rank}</span>`, className: "rank-cell" },
    { label: "Month", render: (row) => escapeHtml(row.month) },
    { label: "New Members", render: (row) => formatInteger(row.newMembers), className: "number-cell" },
    { label: "Renewals", render: (row) => formatInteger(row.renewals), className: "number-cell" },
    { label: "Total Members", render: (row) => formatInteger(row.totalMembers), className: "number-cell" },
    { label: "Revenue", render: (row) => formatCurrency(row.revenue), className: "number-cell" },
    { label: "Activity", render: (row) => progressCell(row.totalMembers, max), className: "table-bar" },
  ], rows);
}

function renderExpirationTable(rows) {
  const max = Math.max(...rows.map((row) => row.members), 1);
  renderTable("expiration-table", [
    { label: "Region", render: (row) => escapeHtml(row.region) },
    { label: "Members", render: (row) => formatInteger(row.members), className: "number-cell" },
    { label: "Earliest", render: (row) => escapeHtml(row.earliestExpiration) },
    { label: "Latest", render: (row) => escapeHtml(row.latestExpiration) },
    { label: "Pipeline", render: (row) => progressCell(row.members, max), className: "table-bar" },
  ], rows);
}

function renderActiveMembersTable(rows) {
  const max = Math.max(...rows.map((row) => row.totalMembers), 1);
  renderTable("active-members-table", [
    { label: "Membership Type", render: (row) => escapeHtml(row.membershipType) },
    { label: "Active Members", render: (row) => formatInteger(row.totalMembers), className: "number-cell" },
    { label: "Share", render: (row) => progressCell(row.totalMembers, max), className: "table-bar" },
  ], rows);
}

function renderTable(tableId, columns, rows) {
  const table = document.getElementById(tableId);
  const thead = table.querySelector("thead");
  const tbody = table.querySelector("tbody");

  thead.innerHTML = `
    <tr>
      ${columns.map((column) => `<th>${escapeHtml(column.label)}</th>`).join("")}
    </tr>
  `;
  tbody.innerHTML = rows.map((row) => `
    <tr>
      ${columns.map((column) => `<td class="${column.className || ""}">${column.render(row)}</td>`).join("")}
    </tr>
  `).join("");
}

function progressCell(value, max) {
  const width = Math.max((value / max) * 100, 2);
  return `
    <div class="table-bar-track">
      <div class="table-bar-fill" style="width: ${width}%;"></div>
    </div>
  `;
}

function setKpi(id, value, formatter) {
  document.getElementById(id).textContent = formatter(value);
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatInteger(value) {
  return new Intl.NumberFormat("en-US", {
    maximumFractionDigits: 0,
  }).format(value || 0);
}

function formatCurrency(value) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(value || 0);
}

function formatCompactCurrency(value) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    notation: "compact",
    maximumFractionDigits: 1,
  }).format(value || 0);
}

function formatPercent(value) {
  return `${Number(value || 0).toFixed(1)}%`;
}
